import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-6xl text-transparent bg-gradient-to-r bg-clip-text from-orange-400 via-yellow-300 to-blue-700">
          Welcome to <a href="https://nextjs.org" className="">Archies Website!</a>
        </h1>


        <div className={styles.grid}>
          

          <a href="/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Achie&#8217;s website!</p>
          </a>

        </div>

        <p className='text-xl py-6'>
          SALE    ON   MAY 12 2022 EVERYTHING     MADE   OUT   OF   PAPER
        </p>
        <p className='text-3xl capitalize'>at carroll park,BK,NY</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
